### ISSUE TITLE
.NET: bad request on verify onboarding

### ISSUE THREAD

**Issue by pb-aw-nl** [DKE-Data/agrirouter#18]
After migration I get this error and I don't know why.

![image](https://github.com/user-attachments/assets/0a87bfab-f2fa-4d0a-bcbf-6df9e8c05a96)

**Comment by oliverrahner** [comment]
Unfortunately, the agrirouter .NET SDK hides the actual error message provided by agrirouter _for the verify call_ as opposed to the onboarding call, where we are handling this in a better way.

The error you are encountering is an invalid signature:
`Failed to verify signature: crypto/rsa: verification error`

Please check if you
* created a public/private key pair from your application page
* copied those keys correctly from the agrirouter UI into your application's configuration
* actually hit "save" after creating the key pair in the UI, because it's a common issue to create and copy the values but then don't save the application afterwards

On a side note, please make sure to use the issue template for submitting bugs, because there are questions providing necessary context for us.

**Comment by pb-aw-nl** [comment]
I recreated the key pair and explicitly hit the save button. The verification and onboarding succeeded now. Next time I will use the bug template (but although this wasn't actually the case)
